// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://repjbpnbfjdsbxoebjze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlcGpicG5iZmpkc2J4b2VianplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMDM1NTEsImV4cCI6MjA3Mzc3OTU1MX0._yG4CSBjnBbNFw1-gV5mkiWZXl_CVdD92ZGAoDAXlGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});